#!/bin/bash

RED="\e[31m"
GREEN="\e[1;32m"
RESET="\e[0m"

# add bin to PATH 
echo $PATH | grep -E ":$HOME/bin[ /]*:" > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "PATH+=':$HOME/bin'" >> "$HOME/.zshrc"
	echo "PATH+=':$HOME/bin'" >> "$HOME/.bashrc"
	export PATH+=':$HOME/bin'
fi


[[ -d "$HOME/bin" ]] || mkdir "$HOME/bin"
[[ -d "$HOME/.local/share/fonts" ]] || mkdir "$HOME/.local/share/fonts"

#------------------------------------------------------------------------------

shell_conf() {
	# install oh_my_zsh
	if [ -d "$HOME/.oh-my-zsh" ]; then
		echo "oh-my-zsh installed"
	else
		sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
		# install power10k 
		git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

		# replace old theme with power10k theme
		old_theme='ZSH_THEME="robbyrussell"'
		new_theme='ZSH_THEME="powerlevel10k/powerlevel10k"'
		file="$HOME/.zshrc"
		sed "s|$old_theme|$new_theme|g" "$file" > "$file.tmp"
		mv "$file.tmp" "$file"
		cd $OLDPWD
		cp fonts/*.ttf $HOME/.local/share/fonts
		echo "open terminal go to preferences set fonts to mesloLGS for you current profile"
	fi
}

#------------------------------------------------------------------------------

install_nvim() {
	cd "$HOME/bin"
	FILE="nvim-linux64.tar.gz"
	nvim --version > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "downloading nvim..."
		curl -# -OL 'https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz'
		tar xzf $FILE
		rm $FILE
		ln -s nvim-linux64/bin/nvim nvim
	fi
	echo -e "${GREEN} nvim [installed] ${RESET}"
	# tput init;
}

#------------------------------------------------------------------------------

install_tilix() {
	cd /tmp
	git clone https://github.com/gnunn1/tilix.git tili
	cd tili
	chmod 744 install.sh
	dub build --build=release
	sudo ./install.sh
}

#------------------------------------------------------------------------------

install_tools() {
	sudo apt install build-essential
	sudo apt install curl
	sudo apt install g++
	sudo apt install zsh
	sudo apt install dub
	sudo apt install gnome-tweaks
}

#------------------------------------------------------------------------------

set_theme() {
	[[ -d "$HOME/.icons" ]] || mkdir "$HOME/.icons"
	[[ -d "$HOME/.themes" ]] || mkdir "$HOME/.themes"

	if [ -d "$HOME/.themes/Dracula" ]; then
		echo "dracula themes set"
	else
		curl -Lo $HOME/.themes/Dracula.zip https://github.com/dracula/gtk/archive/master.zip
		unzip $HOME/.themes/Dracula.zip -d $HOME/.themes/Dracula_dir
		mv $HOME/.themes/Dracula_dir/gtk-master $HOME/.themes/Dracula
		rm -f $HOME/.themes/Dracula.zip
		rmdir $HOME/.themes/Dracula_dir
		gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
		gsettings set org.gnome.desktop.wm.preferences theme "Dracula"
		# cp -r icons/* $HOME/.icons/
		# echo "open tweaks"
		# echo "appearance->icons->afterglow-recolored...."
		# echo "appearance->cursor->vortex-dark-icons"
		# cp -r ./themes/Sweet-Dark $HOME/.themes
		# echo "appearance->shell->sweet-Dark"
		# echo "note you should install User themes to modifier shell"
		# echo "https://extensions.gnome.org/extension/19/user-themes/"
		# echo "you can install it and enable it from here"
		# echo "install Dash to panel extensions"
		# echo "https://extensions.gnome.org/extension/1160/dash-to-panel/"
	fi
}

#------------------------------------------------------------------------------

#------------------------------------------------------------------------------

install_tools
install_nvim
shell_conf
install_tilix
set_theme

